<?php
if (!defined('IVAN_KARSHEV_PARSER_MODULE_FUNCTIONS')) {
    define('IVAN_KARSHEV_PARSER_MODULE_FUNCTIONS', 'ivankarshev.parser');
}
if (!defined('IVAN_KARSHEV_PARSER_MODULE_SEND_PRICE_LIST_MAIL_EVENTNAME')) {
    define('IVAN_KARSHEV_PARSER_MODULE_SEND_PRICE_LIST_MAIL_EVENTNAME', 'PRICE_LIST_EVENT');
}